CREATE SEQUENCE Adres_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE Pracownik_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE Klient_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE Lek_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE Dostawca_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE Zamowienie_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE Stosowanie_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE Recepta_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE Pozycje_recept_seq
MINVALUE 1
START WITH 1
INCREMENT BY 1;