SET ECHO ON
DROP TABLE Adres CASCADE CONSTRAINTS;
DROP TABLE Pracownik CASCADE CONSTRAINTS;
DROP TABLE Klient CASCADE CONSTRAINTS;
DROP TABLE Lek CASCADE CONSTRAINTS;
DROP TABLE Dostawca CASCADE CONSTRAINTS;
DROP TABLE Zamowienie CASCADE CONSTRAINTS;
DROP TABLE Stosowanie CASCADE CONSTRAINTS;
DROP TABLE Recepta CASCADE CONSTRAINTS;
DROP TABLE Pozycje_recept CASCADE CONSTRAINTS;
SET ECHO OFF
