$CLS
PROMPT Menu:
PROMPT 1. CREATE TABLES
PROMPT 2. DROP TABLES
PROMPT 3. INSERT INTO TABLES
PROMPT 4. DELETE FROM TABLES
PROMPT 5. SELECT(VIEWS) FROM TABLES
PROMPT 6. CREATE SEQUENCES AND PROCEDURES NEEDED TO CREATE BASE
PROMPT 7. DROP SEQUENCES AND AND PROCEDURES NEEDED TO CREATE BASE 
PROMPT 8. CREATE FUNTIONS AND PROCEDURES
PROMPT 9. DROP FUNTIONS AND PROCEDURES
PROMPT A. CREATE VIEWS
PROMPT B. DELETE VIEWS
PROMPT C. CREATE TRIGGERS
PROMPT D. DELETE TRIGGERS
PROMPT E. EXEC PROCEDURES OR FUNCTIONS
PROMPT
PROMPT S. CREATE BASE
PROMPT U. DELETE BASE
PROMPT
PROMPT 0. KONIEC+
ACCEPT wybor CHAR FORMAT 'A1' DEFAULT '0' PROMPT '?: '
$CLS
PROMPT wybor = &wybor
@&wybor\main.sql &wybor
PROMPT 
PROMPT # Wcisnij ENTER #
PAUSE
@main.sql